# Auto-generated by CloudVolley AI agent
# Pipeline: customer_etl  Version: v2
from __future__ import annotations

import argparse
import logging

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions, StandardOptions

INPUT_BUCKET  = "gs://anz-cloud-migration-data-input/customer_etl"
OUTPUT_BUCKET = "gs://anz-cloud-migration-data-output/customer_etl/v2"


class ParseRecord(beam.DoFn):
    def process(self, element):
        try:
            fields = element.split(",")
            yield {
                "id":    fields[0].strip(),
                "value": float(fields[1].strip()),
                "label": fields[2].strip() if len(fields) > 2 else "unknown",
            }
        except Exception as exc:
            logging.warning(f"Skipping malformed record: {exc}")


class Enrich(beam.DoFn):
    def process(self, element):
        element["pipeline"] = "customer_etl"
        element["version"]  = "v2"
        yield element


def run(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default=INPUT_BUCKET)
    parser.add_argument("--output", default=OUTPUT_BUCKET)
    known_args, pipeline_args = parser.parse_known_args(argv)

    options = PipelineOptions(pipeline_args)
    options.view_as(StandardOptions).runner = "DataflowRunner"

    with beam.Pipeline(options=options) as p:
        (
            p
            | "Read"    >> beam.io.ReadFromText(known_args.input + "/*.csv")
            | "Parse"   >> beam.ParDo(ParseRecord())
            | "Enrich"  >> beam.ParDo(Enrich())
            | "Write"   >> beam.io.WriteToText(known_args.output)
        )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
