# Auto-generated by CloudVolley AI agent
from __future__ import annotations
import argparse
import logging
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions, StandardOptions

INPUT_BUCKET  = "gs://anz-cloud-migration-data-input/tst_pipeline"
OUTPUT_BUCKET = "gs://anz-cloud-migration-data-output/tst_pipeline/v1"

class ParseRecord(beam.DoFn):
    def process(self, element):
        try:
            fields = element.split(",")
            yield {"id": fields[0].strip(), "value": float(fields[1].strip())}
        except Exception as exc:
            logging.warning(f"Skipping malformed record: {exc}")

class Enrich(beam.DoFn):
    def process(self, element):
        element["pipeline"] = "tst_pipeline"
        yield element

def run(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  default=INPUT_BUCKET)
    parser.add_argument("--output", default=OUTPUT_BUCKET)
    known_args, pipeline_args = parser.parse_known_args(argv)
    options = PipelineOptions(pipeline_args)
    options.view_as(StandardOptions).runner = "DataflowRunner"
    with beam.Pipeline(options=options) as p:
        (
            p
            | "Read"   >> beam.io.ReadFromText(known_args.input + "/*.csv")
            | "Parse"  >> beam.ParDo(ParseRecord())
            | "Enrich" >> beam.ParDo(Enrich())
            | "Write"  >> beam.io.WriteToText(known_args.output)
        )

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
